import json
from pathlib import Path

base_dir = Path(r"c:\Projetos\Temporario\Web\PerfilFamilia\wwwroot\data")
base_dir.mkdir(parents=True, exist_ok=True)

# ===== Pessoas =====
people = [
    ("MÉDICO", ["cuida da saúde", "atua em hospitais ou clínicas", "usa estetoscópio", "lida com diagnósticos"]),
    ("ENFERMEIRO", ["cuida de pacientes", "trabalha em equipe", "usa luvas e materiais", "acompanha tratamentos"]),
    ("DENTISTA", ["cuida dos dentes", "usa cadeira odontológica", "faz restaurações", "usa instrumentos pequenos"]),
    ("VETERINÁRIO", ["cuida de animais", "atende em clínicas", "faz vacinação", "lida com diferentes espécies"]),
    ("FARMACÊUTICO", ["atua com medicamentos", "trabalha em farmácia", "orienta doses", "controla receitas"]),
    ("NUTRICIONISTA", ["monta dietas", "fala sobre alimentação", "trabalha com saúde", "orienta hábitos"]),
    ("FISIOTERAPEUTA", ["trabalha reabilitação", "usa exercícios físicos", "atua com movimentos", "ajuda na recuperação"]),
    ("PSICÓLOGO", ["ouve pessoas", "trabalha com emoções", "faz terapias", "ajuda no bem-estar"]),
    ("PARAMÉDICO", ["atua em resgates", "usa ambulância", "presta primeiros socorros", "age em emergências"]),
    ("TERAPEUTA OCUPACIONAL", ["ajuda em autonomia", "trabalha habilidades", "atua em reabilitação", "faz atividades práticas"]),
    ("PROFESSOR DE MATEMÁTICA", ["ensina números", "usa quadro", "trabalha em sala de aula", "explica cálculos"]),
    ("PROFESSOR DE CIÊNCIAS", ["fala de experimentos", "trabalha com laboratório", "ensina natureza", "usa exemplos práticos"]),
    ("PROFESSOR DE HISTÓRIA", ["fala do passado", "trabalha com datas", "usa livros", "explica acontecimentos"]),
    ("PROFESSOR DE GEOGRAFIA", ["fala de mapas", "explica territórios", "usa atlas", "trabalha com clima"]),
    ("PROFESSOR DE ARTES", ["trabalha criatividade", "usa tintas", "explora cores", "fala de desenhos"]),
    ("PROFESSOR DE EDUCAÇÃO FÍSICA", ["coordena exercícios", "usa quadra", "ensina esportes", "trabalha com alongamento"]),
    ("BIBLIOTECÁRIO", ["organiza livros", "trabalha em biblioteca", "cuida de empréstimos", "lida com catalogação"]),
    ("COORDENADOR PEDAGÓGICO", ["acompanha professores", "planeja aulas", "atua na escola", "organiza projetos"]),
    ("INSTRUTOR DE IDIOMAS", ["ensina outra língua", "treina conversação", "corrige pronúncia", "usa materiais didáticos"]),
    ("TUTOR", ["orienta estudantes", "tira dúvidas", "acompanha estudos", "organiza tarefas"]),
    ("BOMBEIRO", ["combate incêndios", "usa equipamentos de segurança", "atua em resgates", "trabalha com água"]),
    ("POLICIAL", ["garante segurança", "patrulha áreas", "atua em ocorrências", "usa uniforme"]),
    ("GUARDA MUNICIPAL", ["protege locais públicos", "atua nas ruas", "faz rondas", "orienta cidadãos"]),
    ("SALVA-VIDAS", ["trabalha em praias", "vigia banhistas", "faz resgates", "usa boia"]),
    ("AGENTE DE TRÂNSITO", ["organiza o trânsito", "atua em vias", "sinaliza ruas", "aplica regras"]),
    ("VIGIA", ["faz segurança", "trabalha em turnos", "observa entradas", "evita invasões"]),
    ("DELEGADO", ["investiga crimes", "coordena equipes", "trabalha em delegacia", "toma depoimentos"]),
    ("PERITO", ["analisa evidências", "atua em investigações", "usa técnicas científicas", "trabalha com laudos"]),
    ("CANTOR", ["usa a voz", "atua em shows", "ensina música", "faz apresentações"]),
    ("MÚSICO", ["toca instrumentos", "estuda ritmos", "faz ensaios", "atua em bandas"]),
    ("ATOR", ["atua em palco", "interpreta personagens", "decora falas", "usa figurino"]),
    ("ATRIZ", ["atua em teatro", "interpreta papéis", "usa figurino", "trabalha com emoções"]),
    ("DANÇARINO", ["trabalha com movimentos", "faz coreografias", "treina passos", "atua em palco"]),
    ("PINTOR", ["usa tintas", "cria quadros", "trabalha com cores", "usa pincéis"]),
    ("ESCULTOR", ["modela formas", "usa ferramentas", "trabalha com pedra ou argila", "cria esculturas"]),
    ("FOTÓGRAFO", ["usa câmera", "faz ensaios", "capta imagens", "trabalha com luz"]),
    ("CINEASTA", ["faz filmes", "trabalha com roteiro", "dirige cenas", "usa câmeras"]),
    ("ILUSTRADOR", ["cria desenhos", "faz ilustrações", "trabalha com traços", "usa softwares ou papel"]),
    ("CIENTISTA", ["faz pesquisas", "trabalha com hipóteses", "usa laboratório", "analisa dados"]),
    ("BIÓLOGO", ["estuda seres vivos", "trabalha com espécies", "faz observações", "atua na natureza"]),
    ("QUÍMICO", ["trabalha com substâncias", "usa laboratório", "faz reações", "analisa materiais"]),
    ("FÍSICO", ["estuda forças", "trabalha com cálculos", "analisa fenômenos", "usa modelos"]),
    ("GEÓLOGO", ["estuda rochas", "analisa solo", "trabalha com mapas", "observa relevo"]),
    ("ASTRÔNOMO", ["observa estrelas", "usa telescópio", "estuda o céu", "trabalha à noite"]),
    ("METEOROLOGISTA", ["estuda o clima", "faz previsões", "usa dados do tempo", "observa nuvens"]),
    ("PESQUISADOR", ["faz estudos", "organiza dados", "escreve relatórios", "trabalha com método"]),
    ("ECÓLOGO", ["estuda ecossistemas", "trabalha com natureza", "observa impactos", "analisa equilíbrio ambiental"]),
    ("OCEANÓGRAFO", ["estuda oceanos", "analisa marés", "trabalha com água", "faz coletas no mar"]),
    ("PROGRAMADOR", ["escreve código", "trabalha em computador", "cria soluções", "testa sistemas"]),
    ("DESENVOLVEDOR", ["cria softwares", "usa linguagens", "resolve problemas", "trabalha em equipe"]),
    ("ANALISTA DE DADOS", ["trabalha com números", "gera relatórios", "usa planilhas", "faz gráficos"]),
    ("ENGENHEIRO DE SOFTWARE", ["projeta sistemas", "define arquitetura", "coordena desenvolvimento", "garante qualidade"]),
    ("TÉCNICO DE INFORMÁTICA", ["conserta computadores", "instala programas", "configura redes", "faz manutenção"]),
    ("DESIGNER DE INTERFACE", ["cria telas", "trabalha com layout", "pensa em usabilidade", "usa ferramentas gráficas"]),
    ("ADMINISTRADOR DE SISTEMAS", ["gerencia servidores", "cuida de acessos", "monitora serviços", "faz backups"]),
    ("CIENTISTA DE DADOS", ["modela dados", "usa estatística", "cria previsões", "trabalha com algoritmos"]),
    ("ESPECIALISTA EM SEGURANÇA", ["protege sistemas", "analisa riscos", "previne ataques", "atua com políticas"]),
    ("TESTADOR DE SOFTWARE", ["encontra bugs", "faz testes", "verifica qualidade", "segue cenários"]),
    ("ARQUITETO", ["projeta edifícios", "cria plantas", "trabalha com espaços", "planeja construções"]),
    ("ENGENHEIRO CIVIL", ["cuida de obras", "faz cálculos", "supervisiona estruturas", "planeja construções"]),
    ("MESTRE DE OBRAS", ["coordena equipe", "acompanha construção", "organiza materiais", "controla etapas"]),
    ("PEDREIRO", ["assenta tijolos", "faz paredes", "trabalha com argamassa", "atua em obras"]),
    ("CARPINTEIRO", ["trabalha com madeira", "faz móveis", "usa serra", "cria estruturas"]),
    ("ELETRICISTA", ["instala fios", "trabalha com energia", "usa ferramentas", "corrige falhas"]),
    ("ENCANADOR", ["trabalha com água", "instala canos", "conserta vazamentos", "usa ferramentas"]),
    ("AZULEJISTA", ["assenta pisos", "usa rejunte", "trabalha com revestimento", "mede espaços"]),
    ("PINTOR DE PAREDE", ["pinta superfícies", "usa rolos", "prepara tinta", "faz acabamentos"]),
    ("SERRALHEIRO", ["trabalha com metal", "faz portões", "usa solda", "corta estruturas"]),
    ("MOTORISTA", ["dirige veículos", "faz trajetos", "segue rotas", "usa volante"]),
    ("PILOTO DE AVIÃO", ["conduz aeronaves", "usa cabine", "segue plano de voo", "trabalha em aeroportos"]),
    ("MAQUINISTA", ["conduz trem", "atua em ferrovias", "segue sinalização", "controla velocidade"]),
    ("NAVEGADOR", ["orienta rotas", "usa mapas", "atua em navios", "trabalha com bússola"]),
    ("MARINHEIRO", ["trabalha no mar", "atua em navios", "faz manobras", "cuida de manutenção"]),
    ("CICLISTA", ["usa bicicleta", "treina resistência", "participa de provas", "usa capacete"]),
    ("ENTREGADOR", ["faz entregas", "usa mochila", "segue rotas", "cumpre prazos"]),
    ("JARDINEIRO", ["cuida de plantas", "poda árvores", "usa regador", "trabalha em jardins"]),
    ("AGRICULTOR", ["planta e colhe", "trabalha no campo", "usa ferramentas", "lida com lavoura"]),
    ("GUIA DE TRILHA", ["conduz passeios", "atua na natureza", "usa mapa", "orienta grupos"]),
    ("GUARDA FLORESTAL", ["protege áreas", "vigia florestas", "fiscaliza", "atua ao ar livre"]),
    ("PAISAGISTA", ["projeta jardins", "trabalha com plantas", "cria espaços", "pensa em estética"]),
    ("PESCADOR", ["pesca peixes", "usa rede", "trabalha em rios", "faz capturas"]),
    ("APICULTOR", ["cuida de abelhas", "produz mel", "usa caixas", "protege colmeias"]),
    ("BOTÂNICO", ["estuda plantas", "faz pesquisas", "trabalha com espécies", "coleta amostras"]),
    ("COZINHEIRO", ["prepara alimentos", "usa panela", "trabalha em cozinha", "segue receitas"]),
    ("CHEF", ["comanda cozinha", "cria pratos", "coordena equipe", "planeja cardápio"]),
    ("CONFEITEIRO", ["faz doces", "usa forno", "decora bolos", "trabalha com açúcar"]),
    ("PADEIRO", ["faz pães", "usa forno", "amassa farinha", "trabalha de madrugada"]),
    ("BARISTA", ["faz café", "usa máquina", "cuida de grãos", "prepara bebidas"]),
    ("ADVOGADO", ["atua com leis", "defende pessoas", "trabalha com processos", "fala em audiências"]),
    ("JUIZ", ["toma decisões", "atua no tribunal", "interpreta leis", "conduz julgamentos"]),
    ("PROMOTOR", ["representa a sociedade", "atua em processos", "trabalha no fórum", "apresenta denúncias"]),
    ("ARQUEÓLOGO", ["estuda o passado", "faz escavações", "analisa objetos antigos", "trabalha em campo"]),
    ("PUBLICITÁRIO", ["cria campanhas", "trabalha com marcas", "usa criatividade", "atua em agências"]),
    ("JORNALISTA", ["faz reportagens", "entrevista pessoas", "apura informações", "divulga notícias"]),
    ("FONOAUDIÓLOGO", ["cuida da voz", "trabalha com fala", "faz exercícios", "ajuda na comunicação"]),
    ("ENGENHEIRO MECÂNICO", ["trabalha com máquinas", "faz projetos", "analisa peças", "atua em indústrias"]),
    ("ECONOMISTA", ["analisa mercado", "trabalha com finanças", "faz projeções", "estuda economia"]),
    ("CONTADOR", ["organiza contas", "faz balanços", "trabalha com impostos", "atua com empresas"]),
    ("BARTENDER", ["prepara bebidas", "trabalha em bar", "usa coqueteleira", "serve clientes"]),
    ("GUARDA-PARQUE", ["protege áreas naturais", "orienta visitantes", "faz rondas", "atua ao ar livre"]),
]

# ===== Lugares =====
place_types = {
    "PLANÍCIE": ["área plana", "baixa altitude", "acúmulo de sedimentos", "terreno pouco inclinado"],
    "PLANALTO": ["área elevada", "superfície irregular", "ação de erosão", "altitudes maiores"],
    "DEPRESSÃO": ["área rebaixada", "entre regiões mais altas", "inclinação suave", "erosão dominante"],
    "MONTANHA": ["forma elevada", "altitude alta", "encostas íngremes", "vista panorâmica"],
    "ILHA": ["é cercada por água", "pode ser acessada por barco", "tem praias", "vegetação costeira"],
    "VALE": ["fica entre montanhas", "tem rios", "paisagem aberta", "terreno mais baixo"],
    "LAGO": ["água parada", "margens tranquilas", "reflete o céu", "pode ter pesca"],
    "RIO": ["água corrente", "corta a paisagem", "segue um curso", "pode ter pontes"],
    "PRAIA": ["faixa de areia", "som das ondas", "banho de mar", "brisa"],
    "DESERTO": ["pouca chuva", "muita areia", "dunas", "calor intenso"],
    "FLORESTA": ["muitas árvores", "sombra", "sons de animais", "trilhas"],
    "CAVERNA": ["ambiente escuro", "paredes rochosas", "eco", "temperatura mais fresca"],
    "CACHOEIRA": ["queda d'água", "barulho forte", "névoa", "poço para banho"],
    "PARQUE": ["área aberta", "lazer", "bancos", "árvores"],
    "PRAÇA": ["bancos", "encontro de pessoas", "centro", "árvores"],
    "PONTE": ["liga dois pontos", "passagem elevada", "vista para baixo", "estrutura longa"],
    "TORRE": ["bem alta", "vista ampla", "ponto de referência", "estrutura vertical"],
    "FAROL": ["torre alta", "ilumina a costa", "perto do mar", "ponto de referência"],
    "PORTO": ["barcos", "movimento", "água", "embarques"],
    "OBSERVATÓRIO": ["telescópios", "céu noturno", "estrelas", "lugar silencioso"],
}

place_descriptors = [
    "DO SOL", "DA LUA", "DA NEBLINA", "DOS VENTOS", "DAS FLORES", "DAS PEDRAS", "DAS ÁGUAS",
    "DA SERRA", "DA BRUMA", "DO ENCANTO", "DA COSTA", "DA FLORESTA", "DO VALE", "DA PRAIA",
    "DAS ESTRELAS", "DO JARDIM", "DO RIO", "DO LAGO", "DA AREIA", "DO FAROL",
]

# ===== Animais =====
animals = [
    ("CACHORRO", "mamífero", "onívoro", "late", "doméstico"),
    ("GATO", "mamífero", "carnívoro", "mia", "doméstico"),
    ("CAVALO", "mamífero", "herbívoro", "corre rápido", "terrestre"),
    ("VACA", "mamífero", "herbívoro", "produz leite", "terrestre"),
    ("PORCO", "mamífero", "onívoro", "focinho forte", "terrestre"),
    ("CABRA", "mamífero", "herbívoro", "adora escalar", "terrestre"),
    ("OVELHA", "mamífero", "herbívoro", "tem lã", "terrestre"),
    ("COELHO", "mamífero", "herbívoro", "orelhas longas", "terrestre"),
    ("LEÃO", "mamífero", "carnívoro", "rugido forte", "savana"),
    ("TIGRE", "mamífero", "carnívoro", "listras", "floresta"),
    ("LOBO", "mamífero", "carnívoro", "vive em alcateia", "terrestre"),
    ("RAPOSA", "mamífero", "onívoro", "cauda fofa", "terrestre"),
    ("URSO", "mamífero", "onívoro", "pode hibernar", "terrestre"),
    ("PANDA", "mamífero", "herbívoro", "come bambu", "floresta"),
    ("COALA", "mamífero", "herbívoro", "vive em árvores", "floresta"),
    ("CANGURU", "mamífero", "herbívoro", "salta", "terrestre"),
    ("GIRAFA", "mamífero", "herbívoro", "pescoço longo", "savana"),
    ("ZEBRA", "mamífero", "herbívoro", "listras", "savana"),
    ("ELEFANTE", "mamífero", "herbívoro", "tem tromba", "savana"),
    ("RINOCERONTE", "mamífero", "herbívoro", "tem chifre", "savana"),
    ("HIPOPÓTAMO", "mamífero", "herbívoro", "vive na água", "rios"),
    ("VEADO", "mamífero", "herbívoro", "tem galhos", "floresta"),
    ("ALCE", "mamífero", "herbívoro", "galhos grandes", "frio"),
    ("BISÃO", "mamífero", "herbívoro", "corpo robusto", "planícies"),
    ("JAGUAR", "mamífero", "carnívoro", "manchas", "floresta"),
    ("PUMA", "mamífero", "carnívoro", "ágil", "terrestre"),
    ("CAPIVARA", "mamífero", "herbívoro", "vive perto de rios", "rios"),
    ("TATU", "mamífero", "onívoro", "carapaça", "terrestre"),
    ("TAMANDUÁ", "mamífero", "insetívoro", "língua longa", "terrestre"),
    ("MORCEGO", "mamífero", "insetívoro", "voa", "cavernas"),
    ("GALINHA", "ave", "onívoro", "bota ovos", "terrestre"),
    ("GALO", "ave", "onívoro", "canta ao amanhecer", "terrestre"),
    ("PATO", "ave", "onívoro", "nada", "lagos"),
    ("GANSO", "ave", "onívoro", "vive em grupo", "lagos"),
    ("PERU", "ave", "onívoro", "tem penas grandes", "terrestre"),
    ("POMBO", "ave", "granívoro", "vive em cidades", "urbano"),
    ("BEIJA-FLOR", "ave", "nectarívoro", "bate asas rápido", "aéreo"),
    ("TUCANO", "ave", "frugívoro", "bico grande", "floresta"),
    ("PAPAGAIO", "ave", "frugívoro", "imita sons", "floresta"),
    ("CORUJA", "ave", "carnívoro", "noturna", "floresta"),
    ("ÁGUIA", "ave", "carnívoro", "voa alto", "montanhas"),
    ("FALCÃO", "ave", "carnívoro", "mergulha rápido", "aéreo"),
    ("CISNE", "ave", "onívoro", "pescoço longo", "lagos"),
    ("GARÇA", "ave", "carnívoro", "pernas longas", "rios"),
    ("ANDORINHA", "ave", "insetívoro", "voo rápido", "aéreo"),
    ("COBRA", "réptil", "carnívoro", "corpo alongado", "terrestre"),
    ("LAGARTO", "réptil", "insetívoro", "cauda longa", "terrestre"),
    ("IGUANA", "réptil", "herbívoro", "gosta de sol", "terrestre"),
    ("JACARÉ", "réptil", "carnívoro", "vive em rios", "aquático"),
    ("CROCODILO", "réptil", "carnívoro", "mandíbulas fortes", "aquático"),
    ("TARTARUGA", "réptil", "herbívoro", "tem casco", "aquático"),
    ("SAPO", "anfíbio", "insetívoro", "pula", "úmido"),
    ("RÃ", "anfíbio", "insetívoro", "coaxa", "úmido"),
    ("SALAMANDRA", "anfíbio", "insetívoro", "pele úmida", "úmido"),
    ("TUBARÃO", "peixe", "carnívoro", "dentes afiados", "oceano"),
    ("GOLFINHO", "mamífero", "carnívoro", "inteligente", "oceano"),
    ("BALEIA", "mamífero", "carnívoro", "muito grande", "oceano"),
    ("FOCA", "mamífero", "carnívoro", "bigodes", "oceano"),
    ("PEIXE-PALHAÇO", "peixe", "onívoro", "colorido", "oceano"),
    ("SARDINHA", "peixe", "onívoro", "vive em cardumes", "oceano"),
    ("SALMÃO", "peixe", "onívoro", "migra", "rios"),
    ("TILÁPIA", "peixe", "onívoro", "água doce", "rios"),
    ("CARPA", "peixe", "onívoro", "vive em lago", "lagos"),
    ("PIRANHA", "peixe", "carnívoro", "dentes fortes", "rios"),
    ("ABELHA", "inseto", "nectarívoro", "faz mel", "aéreo"),
    ("FORMIGA", "inseto", "onívoro", "vive em colônias", "terrestre"),
    ("BORBOLETA", "inseto", "nectarívoro", "tem asas coloridas", "aéreo"),
    ("JOANINHA", "inseto", "onívoro", "pequena e vermelha", "terrestre"),
    ("GAFANHOTO", "inseto", "herbívoro", "salta", "terrestre"),
    ("CARANGUEJO", "crustáceo", "onívoro", "anda de lado", "praia"),
    ("POLVO", "molusco", "carnívoro", "oito braços", "oceano"),
    ("LULA", "molusco", "carnívoro", "jatos de água", "oceano"),
    ("ESTRELA-DO-MAR", "equinodermo", "carnívoro", "tem braços", "oceano"),
    ("CAVALINHO-MARINHO", "peixe", "carnívoro", "nada na vertical", "oceano"),
    ("URSO-POLAR", "mamífero", "carnívoro", "vive no gelo", "polar"),
    ("LOBO-GUARÁ", "mamífero", "onívoro", "pernas longas", "cerrado"),
    ("ONÇA-PINTADA", "mamífero", "carnívoro", "manchas", "floresta"),
    ("ANTA", "mamífero", "herbívoro", "focinho longo", "floresta"),
    ("PREGUIÇA", "mamífero", "herbívoro", "anda devagar", "árvores"),
    ("ARARA", "ave", "frugívoro", "penas coloridas", "floresta"),
    ("CANÁRIO", "ave", "granívoro", "canta", "aéreo"),
    ("CORVO", "ave", "onívoro", "inteligente", "aéreo"),
    ("LINCE", "mamífero", "carnívoro", "orelhas com tufos", "terrestre"),
    ("GAZELA", "mamífero", "herbívoro", "rápida", "savana"),
    ("SURICATO", "mamífero", "insetívoro", "vive em tocas", "deserto"),
    ("HIENA", "mamífero", "carnívoro", "riso característico", "savana"),
    ("PINGUIM", "ave", "carnívoro", "não voa", "frio"),
    ("AVESTRUZ", "ave", "onívoro", "não voa", "savana"),
    ("EMA", "ave", "onívoro", "corre rápido", "cerrado"),
    ("JABUTI", "réptil", "herbívoro", "tem casco", "terrestre"),
    ("JIBOIA", "réptil", "carnívoro", "corpo alongado", "floresta"),
    ("SUCURI", "réptil", "carnívoro", "vive em rios", "aquático"),
    ("CAMALEÃO", "réptil", "insetívoro", "muda de cor", "terrestre"),
    ("LAGARTIXA", "réptil", "insetívoro", "pequena", "terrestre"),
    ("ARARA-AZUL", "ave", "frugívoro", "penas azuis", "floresta"),
    ("PAVÃO", "ave", "onívoro", "cauda aberta", "terrestre"),
    ("ORNITORRINCO", "mamífero", "carnívoro", "bico achatado", "rios"),
    ("EQUÍDNA", "mamífero", "insetívoro", "tem espinhos", "terrestre"),
    ("GAMBÁ", "mamífero", "onívoro", "cheiro forte", "terrestre"),
    ("PEIXE-BOI", "mamífero", "herbívoro", "vive na água", "rios"),
]

# ===== Coisas =====
objects = [
    ("MOCHILA", ["tem alças", "carrega materiais", "vai nas costas", "usada na escola"]),
    ("CADERNO", ["tem folhas", "serve para escrever", "pode ter espiral", "usado para anotar"]),
    ("LÁPIS", ["tem ponta", "feito de madeira", "apaga com borracha", "serve para escrever"]),
    ("CANETA", ["usa tinta", "tem tampa", "ponta fina", "serve para escrever"]),
    ("RÉGUA", ["mede linhas", "ajuda a desenhar", "tem marcações", "é reta"]),
    ("BORRACHA", ["apaga escrita", "feita de borracha", "pequena", "usada com lápis"]),
    ("APONTADOR", ["aponta lápis", "tem lâmina", "guarda resíduos", "pequeno"]),
    ("ESTOJO", ["guarda materiais", "tem zíper", "porta lápis", "vai na mochila"]),
    ("LIVRO", ["tem páginas", "conta histórias", "tem capa", "usado para ler"]),
    ("MARCADOR", ["destaca textos", "tem tinta forte", "marca páginas", "é colorido"]),
    ("PANELA", ["vai ao fogo", "cozinha alimentos", "tem tampa", "feita de metal"]),
    ("FRIGIDEIRA", ["frita alimentos", "tem cabo", "vai ao fogão", "fundo largo"]),
    ("COLHER", ["ajuda a comer", "tem cabo", "pode ser de metal", "serve para mexer"]),
    ("GARFO", ["tem dentes", "ajuda a comer", "segura alimentos", "tem cabo"]),
    ("FACA", ["corta", "tem lâmina", "usa cabo", "serve na cozinha"]),
    ("PRATO", ["serve comida", "é raso", "fica na mesa", "pode ser de cerâmica"]),
    ("COPO", ["serve bebida", "tem boca larga", "pode ser de vidro", "fica na mesa"]),
    ("XÍCARA", ["bebida quente", "tem alça", "usada para café", "pequena"]),
    ("TÁBUA", ["apoia cortes", "usada na cozinha", "pode ser de madeira", "protege a bancada"]),
    ("ESPÁTULA", ["vira alimentos", "tem cabo", "usada na cozinha", "ajuda a mexer"]),
    ("CELULAR", ["faz chamadas", "tem tela", "usa bateria", "acessa internet"]),
    ("NOTEBOOK", ["tem teclado", "é portátil", "usa bateria", "serve para trabalhar"]),
    ("TECLADO", ["tem teclas", "digitação", "usado no computador", "conectado ao PC"]),
    ("MOUSE", ["controla o cursor", "tem botões", "usado no computador", "pequeno"]),
    ("CARREGADOR", ["recarrega bateria", "tem cabo", "usa energia", "acompanha celular"]),
    ("FONE", ["reproduz som", "vai na orelha", "pode ser bluetooth", "usado para ouvir"]),
    ("CÂMERA", ["tira fotos", "tem lente", "usa bateria", "guarda imagens"]),
    ("RELÓGIO", ["mostra as horas", "tem ponteiros", "pode ser digital", "ajuda no tempo"]),
    ("CONTROLE REMOTO", ["comanda aparelhos", "tem botões", "usa pilha", "aponta para a TV"]),
    ("TABLET", ["tela sensível", "usa toque", "portátil", "lê conteúdos"]),
    ("CADEIRA", ["serve para sentar", "tem quatro pernas", "fica na casa", "apoia as costas"]),
    ("MESA", ["superfície plana", "apoia objetos", "tem pernas", "fica na casa"]),
    ("SOFÁ", ["assento macio", "fica na sala", "acomoda pessoas", "tem almofadas"]),
    ("ALMOFADA", ["macia", "apoia o corpo", "fica no sofá", "tem tecido"]),
    ("LUMINÁRIA", ["ilumina", "tem lâmpada", "fica na mesa", "usa energia"]),
    ("CORTINA", ["cobre janelas", "feita de tecido", "deixa passar luz", "pode ser longa"]),
    ("TAPETE", ["fica no chão", "decora", "feito de tecido", "pode ser grande"]),
    ("ESPELHO", ["mostra reflexo", "feito de vidro", "fica na parede", "ajuda a se ver"]),
    ("TRAVESSEIRO", ["apoia a cabeça", "macio", "usado para dormir", "tem tecido"]),
    ("COBERTOR", ["esquenta", "feito de tecido", "usado para dormir", "macio"]),
    ("ESCOVA", ["tem cerdas", "serve para pentear", "usada no cabelo", "tem cabo"]),
    ("PENTE", ["arruma o cabelo", "tem dentes", "usado no cabelo", "pequeno"]),
    ("SABONETE", ["limpa a pele", "faz espuma", "usado no banho", "tem cheiro"]),
    ("TOALHA", ["seca o corpo", "feita de tecido", "usada após o banho", "macia"]),
    ("CREME DENTAL", ["limpa dentes", "tem sabor", "usado na escovação", "vem em tubo"]),
    ("SHAMPOO", ["lava o cabelo", "tem espuma", "usado no banho", "vem em frasco"]),
    ("DESODORANTE", ["reduz odor", "usado no corpo", "pode ser spray", "tem cheiro"]),
    ("LENÇO", ["usado no nariz", "feito de papel", "descartável", "pequeno"]),
    ("CORTA-UNHAS", ["corta unhas", "tem lâmina", "pequeno", "feito de metal"]),
    ("ESCOVA DE DENTES", ["limpa dentes", "tem cerdas", "usada com pasta", "tem cabo"]),
    ("BOLA", ["redonda", "usada em jogos", "rola", "pode ser esportiva"]),
    ("RAQUETE", ["rebate a bola", "tem cabo", "usada em esportes", "tem rede"]),
    ("CAPACETE", ["protege a cabeça", "tem fecho", "usado em esportes", "segurança"]),
    ("JOELHEIRA", ["protege o joelho", "usada em esportes", "tem elástico", "amortece"]),
    ("TÊNIS", ["vai no pé", "tem cadarço", "serve para caminhar", "protege"]),
    ("BICICLETA", ["tem duas rodas", "usa pedal", "serve para andar", "tem guidão"]),
    ("APITO", ["dá sinal", "faz som", "usado em esportes", "pequeno"]),
    ("LUVA", ["protege a mão", "pode ser de couro", "usada em esportes", "tem cinco dedos"]),
    ("REDE", ["separa a quadra", "usada em esportes", "tem malha", "fica esticada"]),
    ("GARRAFA ESPORTIVA", ["guarda água", "tem tampa", "usada em treinos", "portátil"]),
    ("MALA", ["carrega roupas", "tem alça", "usada em viagens", "pode ter rodinhas"]),
    ("PASSAPORTE", ["documento", "usado em viagens", "tem foto", "serve para entrar em países"]),
    ("BÚSSOLA", ["mostra direção", "tem agulha", "ajuda na orientação", "pequena"]),
    ("MAPA", ["mostra caminhos", "tem lugares", "serve para orientar", "pode ser dobrado"]),
    ("LANTERNA", ["emite luz", "usa pilhas", "portátil", "ajuda no escuro"]),
    ("CANTIL", ["guarda água", "tem tampa", "usado em trilhas", "portátil"]),
    ("CAPA DE CHUVA", ["protege da chuva", "vestível", "leve", "impermeável"]),
    ("MOCHILA DE TRILHA", ["suporta peso", "tem cintas", "usada em trilhas", "maior"]),
    ("BARRACA", ["serve para dormir", "montada no chão", "usada em camping", "tem estacas"]),
    ("SACO DE DORMIR", ["esquenta na noite", "usado em camping", "enrolável", "feito de tecido"]),
    ("VIOLÃO", ["tem cordas", "faz som", "usado na música", "forma de oito"]),
    ("FLAUTA", ["assoprada", "faz som", "tem furos", "instrumento musical"]),
    ("TAMBOR", ["percussão", "faz batidas", "tem pele", "instrumento musical"]),
    ("TECLADO MUSICAL", ["toca notas", "tem teclas", "instrumento musical", "usa energia"]),
    ("MICROFONE", ["amplifica voz", "usado em shows", "capta som", "tem cabo"]),
    ("CAIXA DE SOM", ["reproduz áudio", "tem volume", "usa energia", "tem alto-falante"]),
    ("FONE DE OUVIDO", ["escuta som", "vai na orelha", "pode ser com fio", "isolamento"]),
    ("ESTANTE DE PARTITURA", ["apoia partituras", "usada por músicos", "tem altura", "ajusta inclinação"]),
    ("METRÔNOMO", ["marca o tempo", "usado em música", "faz tic-tac", "ajuda no ritmo"]),
    ("TRIÂNGULO", ["som metálico", "percussão", "tem baqueta", "instrumento musical"]),
    ("GRAMPEADOR", ["grampeia folhas", "usado no escritório", "tem mola", "metal"]),
    ("CLIPS", ["prende papéis", "pequeno", "feito de metal", "usado no escritório"]),
    ("CARIMBO", ["marca documentos", "tem tinta", "usado no escritório", "tem base"]),
    ("PASTA", ["guarda documentos", "organiza folhas", "usada no escritório", "tem abas"]),
    ("AGENDA", ["organiza horários", "tem datas", "usada no dia a dia", "anota compromissos"]),
    ("POST-IT", ["lembretes", "papel adesivo", "pequeno", "colorido"]),
    ("CALCULADORA", ["faz contas", "tem teclas", "usa bateria", "mostra resultados"]),
    ("CANETA MARCADORA", ["marca textos", "tem tinta forte", "usada para destacar", "ponta grossa"]),
    ("QUADRO BRANCO", ["anota", "usa marcador", "fica na parede", "apaga com apagador"]),
    ("TESOURA", ["corta", "tem lâminas", "tem duas alças", "usada no escritório"]),
    ("CADERNETA", ["anota ideias", "tem páginas", "é pequena", "cabe no bolso"]),
    ("PORTA-LÁPIS", ["guarda lápis", "fica na mesa", "organiza materiais", "é rígido"]),
    ("FITA ADESIVA", ["cola papéis", "tem rolo", "é transparente", "usada no escritório"]),
    ("LIXEIRA", ["descarta resíduos", "fica no chão", "tem tampa", "é usada em casa"]),
    ("APAGADOR", ["apaga quadro", "tem feltro", "usado em escolas", "segura com a mão"]),
    ("BORRIFADOR", ["espirra líquido", "tem gatilho", "usado para limpar", "tem frasco"]),
    ("TERMÔMETRO", ["mede temperatura", "tem escala", "usado em saúde", "é pequeno"]),
    ("GUARDA-CHUVA", ["protege da chuva", "abre e fecha", "tem cabo", "é portátil"]),
    ("CHAVE", ["abre portas", "feita de metal", "pequena", "fica no chaveiro"]),
    ("CHAVEIRO", ["guarda chaves", "pode ter argola", "é pequeno", "fica no bolso"]),
]

# ===== Builders =====
def make_people_cards():
    cards = []
    for i, (name, hints) in enumerate(people[:100], 1):
        pistas = ["É uma pessoa"] + hints + ["Tem uma rotina", "É conhecido pelo que faz", "Aprendeu com prática ou estudo"]
        cards.append({"id": i, "categoria": "Pessoa", "resposta": name, "pistas": pistas[:10]})
    return cards

def make_place_cards():
    combos = []
    for t in place_types:
        for d in place_descriptors:
            combos.append(f"{t} {d}")
    combos = combos[:100]
    cards = []
    for i, name in enumerate(combos, 1):
        t = name.split(" ", 1)[0]
        hints = [
            "É um lugar",
            place_types[t][0],
            place_types[t][1],
            place_types[t][2],
            place_types[t][3],
            "Pode receber visitantes",
            "Tem paisagem marcante",
            "Pode aparecer em mapas",
            f"O nome sugere {name.split(' ', 1)[1].lower()}",
            "Pode ser um destino de passeio",
        ]
        cards.append({"id": i, "categoria": "Lugar", "resposta": name, "pistas": hints})
    return cards

def make_animal_cards():
    cards = []
    for i, (name, cls, diet, trait, habitat) in enumerate(animals[:100], 1):
        hints = [
            "É um animal",
            f"É um {cls}",
            f"Sua alimentação é {diet}",
            f"Uma característica: {trait}",
            f"Vive em ambiente {habitat}",
            "É um vertebrado",
            "Tem hábitos próprios",
            "Pode ser visto na natureza",
            "Se locomove de forma característica",
            "Faz parte dos ecossistemas",
        ]
        cards.append({"id": i, "categoria": "Animal", "resposta": name, "pistas": hints})
    return cards

def make_object_cards():
    cards = []
    for i, (name, traits) in enumerate(objects[:100], 1):
        hints = ["É um objeto"] + traits + ["Tem uso no dia a dia", "É fácil de reconhecer", "É vendido em lojas", "Pode ser transportado"]
        cards.append({"id": i, "categoria": "Coisa", "resposta": name, "pistas": hints[:10]})
    return cards

files = {
    "pessoas.json": make_people_cards(),
    "lugares.json": make_place_cards(),
    "animais.json": make_animal_cards(),
    "coisas.json": make_object_cards(),
}

for name, data in files.items():
    (base_dir / name).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")

print("ok", {k: len(v) for k, v in files.items()})
